export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const GET_TODO_REQUEST = 'GET_TODO_REQUEST';
export const GET_TODO_FAILED = 'GET_TODO_FAILED';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
